# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_product_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogProductSelector(object):
    def setupUi(self, DialogProductSelector):
        DialogProductSelector.setObjectName("DialogProductSelector")
        DialogProductSelector.resize(430, 287)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogProductSelector.sizePolicy().hasHeightForWidth())
        DialogProductSelector.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogProductSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listExchange = QtWidgets.QListWidget(DialogProductSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listExchange.sizePolicy().hasHeightForWidth())
        self.listExchange.setSizePolicy(sizePolicy)
        self.listExchange.setMinimumSize(QtCore.QSize(170, 0))
        self.listExchange.setMaximumSize(QtCore.QSize(180, 16777215))
        self.listExchange.setObjectName("listExchange")
        self.horizontalLayout.addWidget(self.listExchange)
        self.tableProduct = QtWidgets.QTableWidget(DialogProductSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableProduct.sizePolicy().hasHeightForWidth())
        self.tableProduct.setSizePolicy(sizePolicy)
        self.tableProduct.setMinimumSize(QtCore.QSize(224, 0))
        self.tableProduct.setMaximumSize(QtCore.QSize(224, 16777215))
        self.tableProduct.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableProduct.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableProduct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProduct.setObjectName("tableProduct")
        self.tableProduct.setColumnCount(3)
        self.tableProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(2, item)
        self.tableProduct.horizontalHeader().setDefaultSectionSize(50)
        self.tableProduct.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableProduct)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogProductSelector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogProductSelector)
        self.buttonBox.accepted.connect(DialogProductSelector.accept)
        self.buttonBox.rejected.connect(DialogProductSelector.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogProductSelector)

    def retranslateUi(self, DialogProductSelector):
        _translate = QtCore.QCoreApplication.translate
        DialogProductSelector.setWindowTitle(_translate("DialogProductSelector", "品种选择"))
        item = self.tableProduct.horizontalHeaderItem(1)
        item.setText(_translate("DialogProductSelector", "名称"))
        item = self.tableProduct.horizontalHeaderItem(2)
        item.setText(_translate("DialogProductSelector", "代码"))
