# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_preference.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogPreference(object):
    def setupUi(self, DialogPreference):
        DialogPreference.setObjectName("DialogPreference")
        DialogPreference.resize(540, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogPreference.sizePolicy().hasHeightForWidth())
        DialogPreference.setSizePolicy(sizePolicy)
        DialogPreference.setMinimumSize(QtCore.QSize(540, 0))
        DialogPreference.setMaximumSize(QtCore.QSize(540, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogPreference)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listExchange = QtWidgets.QListWidget(DialogPreference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listExchange.sizePolicy().hasHeightForWidth())
        self.listExchange.setSizePolicy(sizePolicy)
        self.listExchange.setMinimumSize(QtCore.QSize(140, 0))
        self.listExchange.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listExchange.setObjectName("listExchange")
        self.horizontalLayout.addWidget(self.listExchange)
        self.tableProduct = QtWidgets.QTableWidget(DialogPreference)
        self.tableProduct.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableProduct.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableProduct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProduct.setObjectName("tableProduct")
        self.tableProduct.setColumnCount(6)
        self.tableProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(5, item)
        self.tableProduct.horizontalHeader().setDefaultSectionSize(50)
        self.tableProduct.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableProduct)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPreference)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPreference)
        self.buttonBox.accepted.connect(DialogPreference.accept)
        self.buttonBox.rejected.connect(DialogPreference.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPreference)

    def retranslateUi(self, DialogPreference):
        _translate = QtCore.QCoreApplication.translate
        DialogPreference.setWindowTitle(_translate("DialogPreference", "Preference"))
        item = self.tableProduct.horizontalHeaderItem(0)
        item.setText(_translate("DialogPreference", "名称"))
        item = self.tableProduct.horizontalHeaderItem(1)
        item.setText(_translate("DialogPreference", "代码"))
        item = self.tableProduct.horizontalHeaderItem(2)
        item.setText(_translate("DialogPreference", "最小报价"))
        item = self.tableProduct.horizontalHeaderItem(3)
        item.setText(_translate("DialogPreference", "乘数"))
        item = self.tableProduct.horizontalHeaderItem(4)
        item.setText(_translate("DialogPreference", "多单"))
        item = self.tableProduct.horizontalHeaderItem(5)
        item.setText(_translate("DialogPreference", "空单"))
