# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_exchange_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogExchangeSelector(object):
    def setupUi(self, DialogExchangeSelector):
        DialogExchangeSelector.setObjectName("DialogExchangeSelector")
        DialogExchangeSelector.resize(260, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogExchangeSelector.sizePolicy().hasHeightForWidth())
        DialogExchangeSelector.setSizePolicy(sizePolicy)
        DialogExchangeSelector.setMinimumSize(QtCore.QSize(260, 180))
        DialogExchangeSelector.setMaximumSize(QtCore.QSize(260, 180))
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogExchangeSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listExchange = QtWidgets.QListWidget(DialogExchangeSelector)
        self.listExchange.setObjectName("listExchange")
        self.verticalLayout.addWidget(self.listExchange)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogExchangeSelector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogExchangeSelector)
        self.buttonBox.accepted.connect(DialogExchangeSelector.accept)
        self.buttonBox.rejected.connect(DialogExchangeSelector.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogExchangeSelector)

    def retranslateUi(self, DialogExchangeSelector):
        _translate = QtCore.QCoreApplication.translate
        DialogExchangeSelector.setWindowTitle(_translate("DialogExchangeSelector", "选择交易所"))
